spring:
  application:
    name: ReactTubeBackend
  datasource:
    url: jdbc:mysql://localhost:3306/react_tube
    username: root
    password: spring
    max-active: 10
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  web:
    cors:
      allowed-origins: http://localhost:5173
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

server:
  port: 8080
  error:
    include-message: never
    include-stacktrace: always
    include-exception: true
    include-detail: always

security:
  jwt:
    expiration_minutes: 30
    secret_key: whisperpiasdufgboadfvbouaeybdfipausdfioyugwasdfijauosdcyfvaosdyfg

stream_conf:
  visit:
    max_minutes_between_visits: 1

bucket4j:
  filters:
    - filter-method: servlet
      cache-name: buckets
      rate-limits:
        - expression: "#request.remoteAddr"
          bandwidths:
            - capacity: 10
              time: 1
              unit: minutes

