spring:
  application:
    name: ReactTubeBackend
  datasource:
    url: jdbc:mysql://localhost:3306/react_tube
    username: root
    password: spring
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  web:
    cors:
      allowed-origins: http://localhost:5173

server:
  port: 8080

security:
  jwt:
    expiration_minutes: 30
    secret_key: whisperpiasdufgboadfvbouaeybdfipausdfioyugwasdfijauosdcyfvaosdyfg


