spring:
  application:
    name: ReactTubeBackend
  datasource:
    url: jdbc:mysql://localhost:3306/react_tube
    username: root
    password: spring
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  web:
    cors:
      allowed-origins: http://localhost:5173

server:
  port: 8080
  error:
    include-message: never
    include-stacktrace: never
    include-exception: true
    include-detail: never

security:
  jwt:
    expiration_minutes: 30
    secret_key: whisperpiasdufgboadfvbouaeybdfipausdfioyugwasdfijauosdcyfvaosdyfg

stream_conf:
  visit:
    max_minutes_between_visits: 2
